### ISSUE TITLE
On Mac OS get Python version error even when Python is 2.7

### ISSUE THREAD

**Issue by sharimatz** [Kitware/VIAME#36]
CMake Error at CMakeLists.txt:136 (message):
  Only Python2.7.* is currently supported, please point your
  PYTHON_EXECUTABLE, PYTHON_LIBRARY and PYTHON_INCLUDE_DIR to a Python2.7.*
  install, or set VIAME_DISABLE_PYTHON_CHECK to ignore this message and build
  with other versions at your own peril.

-- Configuring incomplete, errors occurred!
See also "/Users/d3x389/Downloads/VIAME/build/CMakeFiles/CMakeOutput.log".
(viame) we32966:build d3x389$ env | grep PYTHON
PYTHON_EXECUTABLE=/usr/local/bin/python2
PYTHON_LIBRARY=/usr/local/Cellar/python/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7
PYTHON_INCLUDE_DIR=/usr/local/Cellar/python/2.7.14_3/Frameworks/Python.framework/Versions/2.7/include/python2.7

I also tried creating a miniconda environment with Python 2.7 and got the same error.

**Comment by Erotemic** [comment]
Have you tried enabling `VIAME_DISABLE_PYTHON_CHECK`?

**Comment by mattdawkins** [comment]
To identify the python version, VIAME is just doing the following in the main CMakeLists.txt:

  find_package( PythonInterp REQUIRED )
  find_package( PythonLibs REQUIRED )

  if( NOT ${VIAME_DISABLE_PYTHON_CHECK} AND
      ( NOT PYTHON_VERSION_MAJOR EQUAL "2" OR NOT PYTHON_VERSION_MINOR EQUAL "7" ) )

which is a base cmake call. It's possible your paths need to be set to something different on MAC and it's not picking up the version of python you want.

Maybe see the path workaround near the bottom of:

https://github.com/pybind/pybind11/issues/99

I've never tried this on mac with multiple python versions yet. Additionally you could try disabling the check as Jon suggested.

**Comment by mattdawkins** [comment]
FWIW, PYTHON_LIBRARY should point directly to a dylib, see above example in pybind above the close

**Comment by sharimatz** [comment]
Thanks for all the help.  I got it to build finally in a conda environment with Python 2.7.  I wanted to build with that version, since that’s what you’ve tested with.

The build process completed but there were some errors.  I haven’t run make install yet because I’m not sure where it will install.  I’d like to keep it all in the conda environment.  Once it’s installed, is there a demo or test script to run to verify the build?

Thanks again for all your help.
--shari


-------------------------------------------------
Shari Matzner, Ph.D.
Senior Engineer, Operational Systems
Pacific Northwest National Laboratory
Marine Sciences Laboratory
Sequim, WA
360-681-4577

**Comment by mattdawkins** [comment]
Easiest way to test is to run through some of the examples in the 'install/examples' folder, see http://viame.readthedocs.io/en/latest/

There is no 'make install' command, by default it creates an installation in the [build-dir]/install folder.

If you hit any large build issues feel free to post them on here as separate issues. Note: we're in the process right now of re-factoring some of the python interfaces of things which is going to land shortly (switching out boost python -> pybind11)
