### ISSUE TITLE
Fletch does not currently get re-built with new settings

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/VIAME#55]
After changing enable flags, fletch doesn't always get rebuilt with new flags

**Comment by Erotemic** [comment]
Honestly, that's probably ok. It doesn't need to change much and nothing links to it, so its probably fine to have the caveat of "you need to delete it to rebuild" at least until the pytorch maintainers implement an out-of-source build system.

**Comment by mattdawkins** [comment]
No, it's not okay - If I don't have VIVIA turned on at the beginning in VIAME, GUI dependencies in fletch don't get built. If I enable VIVIA, fletch should be updated to have the new requirements enabled (Qt, VTK) which should get rebuilt as soon as the flag is turned on. As it is now, fletch doesn't get rebuilt and vivia just errors out and compile time. It didn't use to do this and I'm not sure which has introduced this.

**Comment by Erotemic** [comment]
Ooops, I thought I was responding to #56 (and my answer doesn't apply there either, so just ignore me).
