### ISSUE TITLE
Referenced Fletch grabs VXL that won't compile with GCC8

### ISSUE THREAD

**Issue by neal-siekierski** [Kitware/VIAME#57]
The currently referenced Fletch version, commit 042b870 (corresponding with the [viame/master branch](https://github.com/Kitware/fletch/tree/viame/master)), grabs a version of VXL that doesn't compile with GCC8. This was fixed in Fletch master with https://github.com/Kitware/fletch/pull/377.

**Comment by mattdawkins** [comment]
I have now forked VIAME into 'release' and 'master' branches, with 'release' being slightly before master (more stable)

On the 'master' branch I have changed it to use roughly fletch master, so this should be resolved
