### ISSUE TITLE
Missing output file for object detection examples

### ISSUE THREAD

**Issue by JoakimHaurum** [Kitware/VIAME#78]
Hi,

I'm currently testing out the VIAME framework, and I've downloaded the Windows binaries (v0.9.9.7). I have tried running the 3 differnet object detection example bat scripts, which seems to run fine as they processes all images, but they does not save an output file. From what I can see in the each of them have a "detector_writer" process which should output a csv file, but when searching in my VIAME folder I cannot find these csv files.

Is this the intended functionality, or am I misunderstanding the code/looking in the wrong location?

I have tried both the CPU and CUDA version of the windows binaries, both downloaded from mirror 2.

I have attached the terminal output for the plugin_explorer.bat and run_yolo.bat files. These were genreated using VIAME from the GPU enabled binaries.

[plugin_explorer_output.txt](https://github.com/Kitware/VIAME/files/3051348/plugin_explorer_output.txt)
[yolo_bat_output.txt](https://github.com/Kitware/VIAME/files/3051349/yolo_bat_output.txt)

Best regards,
Joakim Bruslund Haurum

**Comment by mattdawkins** [comment]
A 'computed_detections.csv' file should get generated wherever you are running the example from, so if this is [install]/examples/object_detection it would be in there.

Maybe if it's install to C:/Program Files and it's not being run with administrative privileges, that's throwing it up and it's failing to write, can you try running it from another directory, for example your desktop? This could be accomplished by moving one of the run .bat scripts in the example tree to a new folder on your desktop and changing VIAME_INSTALL at the top to point to your install location. That or you could run using the project files and run detectors either through the annotation GUI or other to verify they run: 

https://github.com/Kitware/VIAME/tree/master/configs/prj-windows

Also note, the current default models aren't amazing, but they'll be new ones in place in a week or so alongside a new release as we've recently trained newer ones with (significantly) more groundtruth.

**Comment by JoakimHaurum** [comment]
Moving the files out of C:/Program Files solved it! Thank you very much for the quick response.

The current yolov2 models available, how are they trained? Were they pre-trained on imagenet and then fine-tuned on some fish dataset (and if so which one?). I cannot not seem to find this information.

**Comment by mattdawkins** [comment]
Yeah, exactly that process. We're in the process of training updated models with 2-3 different techniques (and are then going to update the default detection models in VIAME). A portion of the training data is available here:

https://www.aamvem.com/data-challenge

**Comment by mattdawkins** [comment]
At some point though I'll probably post the full set I use for training online, it's a fairly different set from the above collected from an assortment of different NOAA centers.

**Comment by JoakimHaurum** [comment]
Thank you for the insight! It's been very helpful :)
